# Generated by Django 4.2.29 on 2026-03-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
