# Generated by Django 4.2.29 on 2026-03-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('duration', models.IntegerField()),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
    ]
